### ISSUE TITLE
"spack clean" should occur in layers that use spack commands

### ISSUE THREAD

**Issue by sknigh** [UO-OACISS/e4s#2]
Steps like this
https://github.com/UO-OACISS/e4s/blob/02df3c022424eed3293ee5e784ff7ad1d842d29f/docker-recipes/ubi7/x86_64/base/Dockerfile#L72-L77

are in many of the base images. When clean is used in this way, no space is reclaimed because the change happens in a new image layer.

**Comment by eugeneswalker** [comment]
Thanks for point this out!
