### ISSUE TITLE
migrate org to https://github.com/E4S-Project

### ISSUE THREAD

**Issue by shahzebsiddiqui** [UO-OACISS/e4s#3]
@sameershende  @eugeneswalker There has been confusion with development of e4s in https://github.com/UO-OACISS/e4s/ and the other org https://github.com/E4S-Project which host the documentation. Please consider moving this repo to E4S-Project. I see E4S namespace is taken so you could try renaming the org. Here are few suggestions

https://github.com/ECP-E4S
https://github.com/ecpe4s
https://github.com/e4secp

You could even put it in https://github.com/exascalecomputingproject which would be an umbrella of all ECP projects for Github and e4s would be there.

**Comment by eugeneswalker** [comment]
Yes, this is confusing. We should centralize. I will take it to the team, but I think `ecpe4s` would make the most sense as that aligns with out Docker Hub. Then we would:
* hub.docker.com/u/ecpe4s
* github.com/ecpe4s

**Comment by shahzebsiddiqui** [comment]
yea `ecpe4s` would be fine too, better take that org name quick while it lasts :)
